version: '3.3'
services:
  frontend:
    container_name: frontend
    build: ./Cliente
    expose:
      - 3000
    volumes:
      - ./Cliente:/code
    command: "npm start"
    networks:
      - frontend_network
  nginx_local:
    build: ./Cliente/serverweb
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - frontend_network
  load_balancer:
    container_name: load_balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend0
      - backend1
      - backend2
    ports:
      - "5000:5000"
    networks:
      service_network:
        ipv4_address: 172.35.78.3
      frontend_network:
        ipv4_address: 192.168.58.3

  backend0:
    container_name : backend0
    restart: always
    build: ./servidor-api
    ports:
      - 3100:3100
    depends_on:
      - mongodb
    volumes:
      - /proc/:/elements/procs/
    environment:
      - PORT=3100
      - MONGO_URI=mongodb://10.10.18.2:27017/redes2
      - HOST=0.0.0.0
      - SERVER_ID=201602782
    networks:
      service_network:
        ipv4_address: 172.35.78.3 
      db_network:
        ipv4_address: 10.10.18.3

  backend1:
    container_name : backend1
    restart: always
    build: ./servidor-api
    ports:
      - 3100:3100
    depends_on:
      - mongodb
    volumes:
      - /proc/:/elements/procs/
    environment:
      - PORT=3100
      - MONGO_URI=mongodb://10.10.18.2:27017/redes2
      - HOST=0.0.0.0
      - SERVER_ID=201408470
    networks:
      service_network:
        ipv4_address: 172.35.78.4 
      db_network:
        ipv4_address: 10.10.18.4

  backend2:
    container_name : backend2
    restart: always
    build: ./servidor-api
    ports:
      - 3100:3100
    depends_on:
      - mongodb
    volumes:
      - /proc/:/elements/procs/
    environment:
      - PORT=3100
      - MONGO_URI=mongodb://10.10.18.2:27017/redes2
      - HOST=0.0.0.0
      - SERVER_ID=201602440
    networks:
      service_network:
        ipv4_address: 172.35.78.5 
      db_network:
        ipv4_address: 10.10.18.5

  mongodb:
    image: 'mongo'
    container_name: mongodb
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
      - /home/mongodb/database:/data/mongodb
    expose:
      - 27017
    restart: unless-stopped
    networks:
      db_network:
        ipv4_address: 10.10.18.2

networks:
  service_network:
    name: service_network
    driver: "bridge"
    ipam:
      driver: default
      config: 
        - subnet: 172.35.78.0/24
  db_network:
    name: db_network
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 10.10.18.0/24
  frontend_network:
    name: frontend_network
    driver: "bridge"
    ipam: 
      driver: default
      config:
        - subnet: 192.168.58.0/24